name: carrot_maps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  cloud_firestore: ^2.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  firebase_core: ^1.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_dotenv: ^5.0.0
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  google_maps_flutter: ^2.0.6
  injectable: ^1.4.1
  json_annotation: ^4.0.1
  location: 4.1.1

dev_dependencies:
  auto_route_generator: ^2.1.0
  bloc_test: ^8.0.2
  build_runner: ^2.0.4
  cloud_firestore_mocks: ^0.9.0+1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  http_mock_adapter: ^0.2.1
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3
  mockito: ^5.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  assets:
    - assets/translations/
    - .env
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
